import { QuizResult } from '@/pages/Quiz';
import QuizMascot from './QuizMascot';

interface QuizResultsProps { result: QuizResult; onRetakeQuiz: () => void; onBackToHome: () => void; }
interface ResultReflection { note: string; tricky: string; strength: string; nextStep: string; quote: string; }

const RESULT_REFLECTIONS: Record<string, ResultReflection> = {
  classic: { note: 'Your enthusiasm is not a problem. It just deserves a tiny map.', tricky: 'You can be halfway into a new plan before your future self has agreed to finish it.', strength: 'When everyone is stuck at the starting line, you are often the person who gets the room moving.', nextStep: 'Before you start, write: “I’m done when…” Give yourself a finish line while the spark is still hot.', quote: 'My enthusiasm is not a problem; it just deserves a tiny map.' },
  inattentive: { note: 'Out of sight is not out of care. Make what matters easier to bump into.', tricky: 'Important things can vanish from view until they suddenly become very, very urgent.', strength: 'When something catches your interest, you can notice connections and ideas other people miss.', nextStep: 'Put one cue directly in your path: the item itself, a note on the door, or one calendar alert.', quote: 'Out of sight is not out of care; I can make what matters easier to bump into.' },
  overfocused: { note: 'You can pause without losing the thing you care about.', tricky: 'Switching tasks, ending a thought loop, or letting a small issue go can take more effort than people see.', strength: 'You can stay with a meaningful idea long enough to find the good bits other people rush past.', nextStep: 'Choose one hand-off cue—a timer, a song, or a stretch—then give yourself one minute to change gears.', quote: 'I can pause without losing the thing I care about.' },
  temporal: { note: 'A loud moment can have a small, steady answer.', tricky: 'A busy moment, interruption, or emotional wobble can land bigger than you expected.', strength: 'You can pick up nuance and emotional detail that helps you understand a situation deeply.', nextStep: 'When a moment feels loud, take three slow breaths and name the next action in six words or fewer.', quote: 'A loud moment can have a small, steady answer.' },
  limbic: { note: 'Small effort is still effort. Today still counts.', tricky: 'When you are low on fuel, even a small task can arrive wearing a dramatic cape.', strength: 'You bring real care and meaning to the people and projects that matter to you.', nextStep: 'Lower the bar on purpose: try the five-minute version and count showing up as a real win.', quote: 'Small effort is still effort, and today still counts.' },
  ringOfFire: { note: 'You do not have to answer every signal at once.', tricky: 'Everything can ask for your attention at the same time, which makes choosing one thing feel weirdly hard.', strength: 'You can generate energy, possibilities, and fast connections at a remarkable pace.', nextStep: 'Make one quieter pocket first: mute one alert, lower one sound, or step away for a minute.', quote: 'I do not have to answer every signal at once.' },
  anxious: { note: 'You can be careful without carrying every possible outcome.', tricky: 'A useful “what if?” can grow into a full-screen warning before you notice it has taken over.', strength: 'You think ahead, notice risks, and care about doing right by people.', nextStep: 'Put both feet on the floor, breathe out a little longer than you breathe in, then choose the kindest two-minute action.', quote: 'I can be careful without carrying every possible outcome.' },
};

export default function QuizResults({ result, onRetakeQuiz, onBackToHome }: QuizResultsProps) {
  const reflection = RESULT_REFLECTIONS[result.resultKey] ?? RESULT_REFLECTIONS.classic;
  return <section className="quiz-result-page"><div className="quiz-shell quiz-result-shell"><div className="quiz-panel quiz-result-panel"><QuizMascot speech="You made it." className={`quiz-result-mascot quiz-result-mascot--${result.resultKey}`} /><div><p className="quiz-eyebrow">YOUR QUIZ PATTERN</p><h1 className="quiz-result-title">Here&apos;s your result.</h1><p className="quiz-result-type">{result.type}</p><p className="quiz-result-description">{result.description}</p><aside className="quiz-result-postit"><b>ONE KIND REMINDER</b><p>{reflection.note}</p></aside><div className="quiz-reflection-grid"><article className="quiz-reflection-card"><strong>THE TRICKY BIT</strong><p>{reflection.tricky}</p></article><article className="quiz-reflection-card is-bright"><strong>YOUR BRIGHT SIDE</strong><p>{reflection.strength}</p></article><article className="quiz-reflection-card is-next"><strong>A KIND NEXT STEP</strong><p>{reflection.nextStep}</p></article></div><blockquote className="quiz-result-quote"><span>A REMINDER FOR YOU</span><p>“{reflection.quote}”</p></blockquote><p className="quiz-result-boundary"><strong>Worth knowing:</strong> we use friendly names here. They map to Dr. Amen/Amen Clinics&apos; seven-type framework: Classic ADD, Inattentive ADD, Overfocused ADD, Temporal Lobe ADD, Limbic ADD, Ring of Fire ADD, and Anxious ADD. Your result maps to <strong>{result.sourceLabel}</strong>. This is for self-reflection, not a clinical diagnosis or assessment; a qualified clinician can help with formal ADHD evaluation.</p><div className="quiz-result-actions"><button onClick={onRetakeQuiz} className="quiz-secondary-action">RETAKE QUIZ</button><button onClick={onBackToHome} className="quiz-primary-action">TRY THE TASK TOOL →</button></div></div></div></div></section>;
}
