import { QuizResult } from '@/pages/Quiz';
import QuizMascot from './QuizMascot';

interface QuizResultsProps { result: QuizResult; onRetakeQuiz: () => void; onBackToHome: () => void; }
interface ResultReflection { note: string; tricky: string; strength: string; nextStep: string; }

const RESULT_REFLECTIONS: Record<string, ResultReflection> = {
  classic: { note: 'Your spark is real. Let’s give it a finish line.', tricky: 'Momentum can sprint ahead of the plan, leaving the finish line behind.', strength: 'You can bring spark, courage, and momentum to a stuck room.', nextStep: 'Pick one tiny “done” line before you begin.' },
  inattentive: { note: 'The thought is still there. Let’s make it easier to spot.', tricky: 'Important things can drift out of view until they become urgent.', strength: 'When something clicks, you can bring unusually deep thought to it.', nextStep: 'Put the next action where your eyes will actually meet it.' },
  overfocused: { note: 'A strong grip can be useful. We just need a gentle gear shift.', tricky: 'Switching gears can feel like asking a train to turn on a coin.', strength: 'You can stay with a meaningful idea long enough to notice the good bits.', nextStep: 'Set one gentle “switch tracks” cue before you dive in.' },
  temporal: { note: 'The moment landed loudly. A smaller start can help.', tricky: 'A busy moment can land loudly and throw your internal rhythm off.', strength: 'You may notice nuance, memory cues, and emotional detail others miss.', nextStep: 'Shrink the next action until it feels safe to start.' },
  limbic: { note: 'Low-gear days still count. Small is a valid size.', tricky: 'On a low-gear day, the emotional weight of a task can make it look enormous.', strength: 'You can bring care and meaning to the things that matter to you.', nextStep: 'Choose the smallest possible version of today’s task.' },
  ringOfFire: { note: 'That is a lot of input. One quieter signal is enough for now.', tricky: 'It can feel like sixteen tabs are all playing at full volume.', strength: 'Your mind can generate energy and ideas at a remarkable pace.', nextStep: 'Turn down one input, then choose one task—not all sixteen.' },
  anxious: { note: 'You’re not “too much.” Let’s give your brain one safe thing to do.', tricky: '“What if?” can grow from a useful check into a full-screen warning.', strength: 'You think ahead, notice risks, and care about doing right by people.', nextStep: 'Give yourself a two-minute first step. No perfect plan required.' },
};

export default function QuizResults({ result, onRetakeQuiz, onBackToHome }: QuizResultsProps) {
  const reflection = RESULT_REFLECTIONS[result.resultKey] ?? RESULT_REFLECTIONS.classic;
  return <section className="quiz-result-page"><div className="quiz-shell quiz-result-shell"><div className="quiz-panel quiz-result-panel"><QuizMascot speech="You made it." /><div><p className="quiz-eyebrow">YOUR ADHD TYPE</p><h1 className="quiz-result-title">Here&apos;s your result.</h1><p className="quiz-result-type">{result.type}</p><p className="quiz-result-description">{result.description}</p><aside className="quiz-result-postit"><b>ONE KIND REMINDER</b><p>{reflection.note}</p></aside><div className="quiz-reflection-grid"><article className="quiz-reflection-card"><strong>THE TRICKY BIT</strong><p>{reflection.tricky}</p></article><article className="quiz-reflection-card is-bright"><strong>YOUR BRIGHT SIDE</strong><p>{reflection.strength}</p></article><article className="quiz-reflection-card is-next"><strong>A KIND NEXT STEP</strong><p>{reflection.nextStep}</p></article></div><p className="quiz-result-boundary"><strong>Worth knowing:</strong> this quiz uses Dr. Amen/Amen Clinics&apos; seven-type framework for self-reflection. It is not a clinical diagnosis or assessment; a qualified clinician can help with formal ADHD evaluation.</p><div className="quiz-result-actions"><button onClick={onRetakeQuiz} className="quiz-secondary-action">RETAKE QUIZ</button><button onClick={onBackToHome} className="quiz-primary-action">TRY THE TASK TOOL →</button></div></div></div></div></section>;
}
