import { QuizResult } from '@/pages/Quiz';
import QuizMascot from './QuizMascot';

interface QuizResultsProps { result: QuizResult; onRetakeQuiz: () => void; onBackToHome: () => void; }
interface ResultReflection { note: string; tricky: string; strength: string; nextStep: string; quote: string; }

const RESULT_REFLECTIONS: Record<string, ResultReflection> = {
  classic: { note: 'Your spark is real. Let’s give it a finish line.', tricky: 'Momentum can sprint ahead of the plan, leaving the finish line behind.', strength: 'You can bring spark, courage, and momentum to a stuck room.', nextStep: 'Before you begin, write one sentence that tells future-you what “done enough” looks like.', quote: 'I can bring the spark and still choose a finish line.' },
  inattentive: { note: 'The thought is still there. Let’s make it easier to spot.', tricky: 'Important things can drift out of view until they become urgent.', strength: 'When something clicks, you can bring unusually deep thought to it.', nextStep: 'Put one visual cue directly in your path: a note on the door, the item itself, or a calendar alert.', quote: 'Out of sight is not out of care; I can make what matters easier to find.' },
  overfocused: { note: 'A strong grip can be useful. We just need a gentle gear shift.', tricky: 'Switching gears can feel like asking a train to turn on a coin.', strength: 'You can stay with a meaningful idea long enough to notice the good bits.', nextStep: 'Choose a gentle hand-off cue—a timer, a song, or a stretch—then give yourself one minute to switch gears.', quote: 'I can pause without losing what matters to me.' },
  temporal: { note: 'The moment landed loudly. A smaller start can help.', tricky: 'A busy moment can land loudly and throw your internal rhythm off.', strength: 'You may notice nuance, memory cues, and emotional detail others miss.', nextStep: 'When a moment feels loud, pause for three slow breaths and name the next action in six words or fewer.', quote: 'I can meet a loud moment with a smaller, steadier response.' },
  limbic: { note: 'Low-gear days still count. Small is a valid size.', tricky: 'On a low-gear day, the emotional weight of a task can make it look enormous.', strength: 'You can bring care and meaning to the things that matter to you.', nextStep: 'Lower the bar on purpose: try a five-minute version, then count showing up as a real win.', quote: 'Small effort is still real effort, and today counts.' },
  ringOfFire: { note: 'That is a lot of input. One quieter signal is enough for now.', tricky: 'It can feel like sixteen tabs are all playing at full volume.', strength: 'Your mind can generate energy and ideas at a remarkable pace.', nextStep: 'Make a quieter pocket first: mute one alert, lower one sound, or step away for a minute before deciding.', quote: 'I do not have to answer every signal at once.' },
  anxious: { note: 'You’re not “too much.” Let’s give your brain one safe thing to do.', tricky: '“What if?” can grow from a useful check into a full-screen warning.', strength: 'You think ahead, notice risks, and care about doing right by people.', nextStep: 'Put both feet on the floor, breathe out a little longer than you breathe in, then choose the kindest two-minute action.', quote: 'I can be careful without carrying every possible outcome.' },
};

export default function QuizResults({ result, onRetakeQuiz, onBackToHome }: QuizResultsProps) {
  const reflection = RESULT_REFLECTIONS[result.resultKey] ?? RESULT_REFLECTIONS.classic;
  return <section className="quiz-result-page"><div className="quiz-shell quiz-result-shell"><div className="quiz-panel quiz-result-panel"><QuizMascot speech="You made it." /><div><p className="quiz-eyebrow">YOUR QUIZ PATTERN</p><h1 className="quiz-result-title">Here&apos;s your result.</h1><p className="quiz-result-type">{result.type}</p><p className="quiz-result-description">{result.description}</p><aside className="quiz-result-postit"><b>ONE KIND REMINDER</b><p>{reflection.note}</p></aside><div className="quiz-reflection-grid"><article className="quiz-reflection-card"><strong>THE TRICKY BIT</strong><p>{reflection.tricky}</p></article><article className="quiz-reflection-card is-bright"><strong>YOUR BRIGHT SIDE</strong><p>{reflection.strength}</p></article><article className="quiz-reflection-card is-next"><strong>A KIND NEXT STEP</strong><p>{reflection.nextStep}</p></article></div><blockquote className="quiz-result-quote"><span>A REMINDER FOR YOU</span><p>“{reflection.quote}”</p></blockquote><p className="quiz-result-boundary"><strong>Worth knowing:</strong> we use friendly names here. They map to Dr. Amen/Amen Clinics&apos; seven-type framework: Classic ADD, Inattentive ADD, Overfocused ADD, Temporal Lobe ADD, Limbic ADD, Ring of Fire ADD, and Anxious ADD. Your result maps to <strong>{result.sourceLabel}</strong>. This is for self-reflection, not a clinical diagnosis or assessment; a qualified clinician can help with formal ADHD evaluation.</p><div className="quiz-result-actions"><button onClick={onRetakeQuiz} className="quiz-secondary-action">RETAKE QUIZ</button><button onClick={onBackToHome} className="quiz-primary-action">TRY THE TASK TOOL →</button></div></div></div></div></section>;
}
